version: "3.8"

networks:
  gv_network:
    driver: bridge

volumes:
  prometheus_data:
  postgres_data:
  grafana_data:

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres:latest
    ports:
      - "5433:5432"  # Mapeia a porta 5432 do container para a 5433 do host
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestao_vagas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gv_network
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gv_network
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - gv_network
