name: Gestao de Vagas Application

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with: 
          distribution: temurin
          java-version: 21

      - name: Build project
        run: mvn clean install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mrfmarcos/gestao_vagas .

      - name: Push Docker image
        run: docker push mrfmarcos/gestao_vagas

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Docker image from Docker Hub
        run: docker pull mrfmarcos/gestao_vagas:latest

      - name: Remove existing container (if any)
        run: docker rm -f gestao_vagas || true

      - name: Run Docker container gestao_vagas
        run: |
          docker run -d -p 8080:8080 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e DATABASE_PASSWORD='${{ secrets.DATABASE_PASSWORD }}' \
            -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
            --name gestao-vagas mrfmarcos/gestao_vagas:latest
